<?xml version="1.0" encoding="utf-8"?>
<test-run id="2" testcasecount="3" result="Failed(Child)" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="0" engine-version="3.5.0.0" clr-version="4.0.30319.42000" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.0935633">
  <test-suite type="TestSuite" id="1008" name="My Project" fullname="My Project" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.093563" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="0">
    <properties />
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="Assembly" id="1013" name="Tests.dll" fullname="/MyProject/Library/ScriptAssemblies/Tests.dll" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.067697" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="0">
      <properties>
        <property name="_PID" value="20328" />
        <property name="_APPDOMAIN" value="Unity Child Domain" />
        <property name="platform" value="EditMode" />
      </properties>
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="1009" name="MathTests" fullname="MathTests" classname="MathTests" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.053753" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="0">
        <properties />
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="1011" name="TestAddition" fullname="MathTests.TestAddition" methodname="TestAddition" classname="MathTests" runstate="Runnable" seed="168801558" result="Failed" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.020898" asserts="0">
          <properties />
          <failure>
            <message><![CDATA[  Expected: 19
  But was:  21
]]></message>
            <stack-trace><![CDATA[at MathTests.TestAddition () [0x00001] in MyProject\Assets\Tests\MathTests.cs:18
]]></stack-trace>
          </failure>
        </test-case>
        <test-case id="1012" name="TestMultiplication" fullname="MathTests.TestMultiplication" methodname="TestMultiplication" classname="MathTests" runstate="Runnable" seed="1625636288" result="Failed" label="Error" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.001352" asserts="0">
          <properties />
          <failure>
            <message><![CDATA[System.Exception : Exception of type 'System.Exception' was thrown.]]></message>
            <stack-trace><![CDATA[  at MathTests.TestMultiplication () [0x00001] in MyProject\Assets\Tests\MathTests.cs:24 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <695d1cc93cca45069c528c15c9fdd749>:0 ]]></stack-trace>
          </failure>
        </test-case>
        <test-case id="1010" name="TestSubtraction" fullname="MathTests.TestSubtraction" methodname="TestSubtraction" classname="MathTests" runstate="Runnable" seed="1969748331" result="Passed" start-time="2021-11-10 16:33:17Z" end-time="2021-11-10 16:33:17Z" duration="0.001851" asserts="0">
          <properties />
        </test-case>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>